import type { ThemeBase, ThemeName } from '@/types';

const neutral: ThemeBase = {
  dark: {
    accent: '#262626',
    accentForeground: '#fafafa',
    background: '#0a0a0a',
    border: '#262626',
    card: '#0a0a0a',
    cardForeground: '#fafafa',
    destructive: '#7f1d1d',
    destructiveForeground: '#fafafa',
    foreground: '#fafafa',
    input: '#262626',
    mode: 'dark',
    muted: '#262626',
    mutedForeground: '#a3a3a3',
    name: 'neutral',
    popover: '#0a0a0a',
    popoverForeground: '#fafafa',
    primary: '#fafafa',
    primaryForeground: '#171717',
    secondary: '#474747',
    secondaryForeground: '#fafafa',
  },
  light: {
    accent: '#f5f5f5',
    accentForeground: '#171717',
    background: '#ffffff',
    border: '#e5e5e5',
    card: '#ffffff',
    cardForeground: '#0a0a0a',
    destructive: '#dc2626',
    destructiveForeground: '#fafafa',
    foreground: '#0a0a0a',
    input: '#e5e5e5',
    mode: 'light',
    muted: '#f5f5f5',
    mutedForeground: '#737373',
    name: 'neutral',
    popover: '#ffffff',
    popoverForeground: '#0a0a0a',
    primary: '#171717',
    primaryForeground: '#fafafa',
    secondary: '#f5f5f5',
    secondaryForeground: '#171717',
  },
};

const stonks: ThemeBase = {
  dark: {
    accent: '#261C1C',
    accentForeground: '#FAFBFB',
    background: '#0B0A09',
    border: '#261C1C',
    card: '#0B0A09',
    cardForeground: '#FAFBFB',
    destructive: '#731212',
    destructiveForeground: '#FAFBFB',
    foreground: '#FAFBFB',
    input: '#261C1C',
    mode: 'dark',
    muted: '#282524',
    mutedForeground: '#FAFAF9',
    name: 'stonks',
    popover: '#0B0A09',
    popoverForeground: '#FAFBFB',
    primary: '#FBCB14',
    primaryForeground: '#421F05',
    secondary: '#261C1C',
    secondaryForeground: '#FAFBFB',
  },
  light: {
    accent: '#F4F4F8',
    accentForeground: '#1C1917',
    background: '#FFFFFF',
    border: '#E6E3E3',
    card: '#FFFFFF',
    cardForeground: '#0B0A09',
    destructive: '#B81010',
    destructiveForeground: '#FAFBFB',
    foreground: '#0B0A09',
    input: '#E6E3E3',
    mode: 'light',
    muted: '#F4F4F8',
    mutedForeground: '#726E69',
    name: 'stonks',
    popover: '#FFFFFF',
    popoverForeground: '#0B0A09',
    primary: '#FFA005',
    primaryForeground: '#481400',
    secondary: '#F4F4F8',
    secondaryForeground: '#1C1917',
  },
};

const aesir: ThemeBase = {
  dark: {
    accent: 'rgb(28, 38, 44)',
    accentForeground: '#FAFBFB',
    background: 'rgb(12, 3, 11)',
    border: 'rgb(28, 38, 44)',
    card: 'rgb(12, 3, 11)',
    cardForeground: '#FAFBFB',
    destructive: '#731212',
    destructiveForeground: '#FAFBFB',
    foreground: '#FAFBFB',
    input: 'rgb(28, 38, 44)',
    mode: 'dark',
    muted: 'rgb(28, 38, 44)',
    mutedForeground: 'rgb(95, 107, 115)',
    name: 'aesir',
    popover: 'rgb(12, 3, 11)',
    popoverForeground: '#FAFBFB',
    primary: 'rgb(37, 102, 231)',
    primaryForeground: 'rgb(28, 6, 22)',
    secondary: 'rgb(28, 38, 44)',
    secondaryForeground: '#FAFBFB',
  },
  light: {
    accent: 'rgb(230, 232, 237)',
    accentForeground: 'rgb(28, 6, 22)',
    background: 'rgb(255, 255, 255)',
    border: 'rgb(230, 232, 237)',
    card: 'rgb(255, 255, 255)',
    cardForeground: 'rgb(12, 3, 11)',
    destructive: 'rgb(184, 16, 16)',
    destructiveForeground: '#FAFBFB',
    foreground: 'rgb(12, 3, 11)',
    input: 'rgb(230, 232, 237)',
    mode: 'light',
    muted: 'rgb(230, 232, 237)',
    mutedForeground: 'rgb(95, 107, 115)',
    name: 'aesir',
    popover: 'rgb(255, 255, 255)',
    popoverForeground: 'rgb(12, 3, 11)',
    primary: 'rgb(37, 102, 231)',
    primaryForeground: '#FAFBFB',
    secondary: 'rgb(230, 232, 237)',
    secondaryForeground: 'rgb(28, 6, 22)',
  },
};

export const textType = {
  destructive: 'destructiveForeground',
  muted: 'mutedForeground',
  primary: 'primaryForeground',
  secondary: 'foreground',
} as const;

export const backgroundType = {
  destructive: 'destructive',
  muted: 'muted',
  primary: 'primary',
  secondary: 'background',
} as const;

export const defaultTheme = neutral.dark;

export const themes: { [key in ThemeName]: ThemeBase } = {
  aesir,
  neutral,
  stonks,
};
