// Long-lived ML-KEM-512 identity keypair + per-contact KEM state.
//
// Why a dedicated module: the rest of the messaging code shouldn't have to
// know whether the keypair lives in Keychain or memory, or how the per-
// contact handshake state is persisted. Wallet + syncer just ask for the
// public bytes to advertise, the secret bytes to decapsulate, and the
// per-contact crypto state to encrypt/decrypt with.
//
// Storage:
//   - Identity keypair: react-native-keychain, generic password under the
//     service label 'kem-identity'. Stored as `${skHex}|${pkHex}` so we keep
//     both halves together and don't have to recompute the pubkey on every
//     load. ml_kem512 keypair is ~2.4 KB hex, well within Keychain limits.
//   - Per-contact KEM state: SQLite `contacts` table — we already kept the
//     `messagekey` column reserved for exactly this. A new `pending_kem_ct`
//     column stores the ciphertext we owe the peer on our next outgoing
//     send (cleared once shipped).

import * as Keychain from 'react-native-keychain';
import {
  generateKemKeypair,
  encapsulate,
  decapsulate,
  hexToUint,
  uintToHex,
  type IdentityKemKey,
} from 'hugin-crypto';
import {
  getContacts,
  updateContactKemState,
} from '../bare/sqlite';

const KEYCHAIN_SERVICE = 'kem-identity';

let cachedIdentity: IdentityKemKey | null = null;

/**
 * Load the device's long-lived ML-KEM identity keypair, generating it on
 * first launch. Caller (Wallet.init / pushnotifications.init) invokes this
 * once at startup; we cache in module scope so per-message paths are cheap.
 */
export async function loadOrCreateIdentity(): Promise<IdentityKemKey> {
  if (cachedIdentity) return cachedIdentity;

  try {
    const creds = await Keychain.getGenericPassword({ service: KEYCHAIN_SERVICE });
    if (creds && creds.password.includes('|')) {
      const [skHex, pkHex] = creds.password.split('|');
      cachedIdentity = {
        secretKey: hexToUint(skHex),
        publicKey: hexToUint(pkHex),
      };
      return cachedIdentity;
    }
  } catch (e) {
    console.warn('[identity] Keychain read failed, generating fresh keypair:', e);
  }

  const kp = generateKemKeypair();
  const blob = `${uintToHex(kp.secretKey)}|${uintToHex(kp.publicKey)}`;
  try {
    await Keychain.setGenericPassword('kem-identity', blob, {
      service: KEYCHAIN_SERVICE,
      accessible: Keychain.ACCESSIBLE.ALWAYS,
    });
  } catch (e) {
    console.error('[identity] Failed to persist ML-KEM identity:', e);
    // Continue anyway — we have an in-memory keypair for this session, but
    // it'll be regenerated next launch and existing contacts will need to
    // re-handshake. The user sees this as 'a peer that suddenly forgot us'.
  }
  cachedIdentity = kp;
  return kp;
}

/** The 800-byte ML-KEM public key, hex-encoded. Cheap once loaded. */
export async function identityPublicKey(): Promise<string> {
  const kp = await loadOrCreateIdentity();
  return uintToHex(kp.publicKey);
}

/** Raw public key bytes — what hugin-crypto wants. */
export async function identityPublicKeyBytes(): Promise<Uint8Array> {
  const kp = await loadOrCreateIdentity();
  return kp.publicKey;
}

/** Secret key bytes for decapsulation. Never expose outside the device. */
export async function identitySecretKeyBytes(): Promise<Uint8Array> {
  const kp = await loadOrCreateIdentity();
  return kp.secretKey;
}

// ---------------------------------------------------------------------------
// Per-contact KEM state — read/write through the SQLite contacts row.
// ---------------------------------------------------------------------------

/** What the message-encrypt path needs to know about a contact. */
export interface ContactCrypto {
  /**
   * 32-byte shared secret. Presence ≡ handshake completed — this is the only
   * field you need to look at to answer "have we finished the ML-KEM
   * exchange with this contact?".
   */
  messageKey?: Uint8Array;
  /**
   * The capsule we generated by encapsulating against the peer's kem_pub
   * but haven't shipped yet. Include on the next outgoing message, then
   * clear with `markKemCapsuleDelivered`. Transient — usually populated for
   * one message at most.
   */
  pendingKemCapsule?: Uint8Array;
}

/**
 * Lookup the contact's current crypto state. Returns empty object for fresh
 * contacts (they get our kem_pub on the initial send).
 */
export async function getContactCrypto(address: string): Promise<ContactCrypto> {
  const contacts = await getContacts();
  const c = contacts.find((x: any) => x.address === address);
  if (!c) return {};
  const out: ContactCrypto = {};
  if (c.messagekey && typeof c.messagekey === 'string' && c.messagekey.length === 64) {
    out.messageKey = hexToUint(c.messagekey);
  }
  if (c.pending_kem_capsule && typeof c.pending_kem_capsule === 'string' && c.pending_kem_capsule.length > 0) {
    out.pendingKemCapsule = hexToUint(c.pending_kem_capsule);
  }
  return out;
}

/**
 * Bob's path: received Alice's `kem_pub`. Immediately encapsulate, persist
 * both halves on the contact row, and stash the ciphertext to ship on the
 * next outgoing send (so a single round-trip closes the handshake).
 */
export async function onReceivedPeerKemPub(
  address: string,
  peerKemPub: Uint8Array,
): Promise<{ messageKey: Uint8Array; pendingKemCapsule: Uint8Array }> {
  const { ciphertext, sharedSecret } = encapsulate(peerKemPub);
  await updateContactKemState(address, {
    messagekey: uintToHex(sharedSecret),
    pending_kem_capsule: uintToHex(ciphertext),
  });
  return { messageKey: sharedSecret, pendingKemCapsule: ciphertext };
}

/**
 * Alice's path: opened Bob's reply, hugin-crypto decapsulated for us and
 * handed back the shared secret. Persist as the contact's messageKey.
 */
export async function onReceivedKemCapsule(
  address: string,
  sharedSecret: Uint8Array,
): Promise<void> {
  await updateContactKemState(address, {
    messagekey: uintToHex(sharedSecret),
  });
}

/** After we ship the kem capsule in an outgoing message, clear it. */
export async function markKemCapsuleDelivered(address: string): Promise<void> {
  await updateContactKemState(address, { pending_kem_capsule: '' });
}

/** Test-only — drop cached identity so the next call re-reads Keychain. */
export function _resetCache(): void {
  cachedIdentity = null;
}
